[package]
name = "async_rust_practice"
version = "0.1.0"
authors = ["qaisar"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.12"
async-std = "1.9.0"
